// const categoriesArr = [
//   'Electronics',
//   'Clothing',
//   'Home Garden',
//   'Toys Games',
//   'Sports Outdoors',
//   'Books Media',
//   'Beauty Personal Care',
//   'Automotive',
//   'Health Wellness',
//   'Jewelry Watches',
// ];
export const productTags = ['New', 'Sale'];
export const categoriesWithSubCategoriesArr = [
  {
    name: 'Electronics',
    subCategories: [
      { name: 'Mobile Phones' },
      { name: 'Laptops' },
      { name: 'Cameras' },
      { name: 'Televisions' },
      { name: 'Headphones' },
    ],
  },
  {
    name: 'Clothing',
    subCategories: [
      { name: 'Men' },
      { name: 'Women' },
      { name: 'Kids' },
      { name: 'Accessories' },
      { name: 'Footwear' },
    ],
  },
  {
    name: 'Home Garden',
    subCategories: [
      { name: 'Furniture' },
      { name: 'Kitchen' },
      { name: 'Decor' },
      { name: 'Garden Tools' },
      { name: 'Lighting' },
    ],
  },
  {
    name: 'Toys Games',
    subCategories: [
      { name: 'Action Figures' },
      { name: 'Board Games' },
      { name: 'Dolls' },
      { name: 'Puzzles' },
      { name: 'Outdoor Play' },
    ],
  },
  {
    name: 'Sports Outdoors',
    subCategories: [
      { name: 'Fitness' },
      { name: 'Camping' },
      { name: 'Cycling' },
      { name: 'Fishing' },
      { name: 'Team Sports' },
    ],
  },
  {
    name: 'Books Media',
    subCategories: [
      { name: 'Fiction' },
      { name: 'Non-Fiction' },
      { name: 'Comics' },
      { name: 'Magazines' },
      { name: 'Music' },
    ],
  },
  {
    name: 'Beauty Personal Care',
    subCategories: [
      { name: 'Skincare' },
      { name: 'Haircare' },
      { name: 'Makeup' },
      { name: 'Fragrances' },
      { name: 'Personal Hygiene' },
    ],
  },
  {
    name: 'Automotive',
    subCategories: [
      { name: 'Car Accessories' },
      { name: 'Motorcycle Accessories' },
      { name: 'Car Electronics' },
      { name: 'Car Care' },
      { name: 'Tools Equipment' },
    ],
  },
  {
    name: 'Health Wellness',
    subCategories: [
      { name: 'Supplements' },
      { name: 'Medical Supplies' },
      { name: 'Fitness Equipment' },
      { name: 'Personal Care' },
      { name: 'Wellness' },
    ],
  },
  {
    name: 'Jewelry Watches',
    subCategories: [
      { name: "Men's Jewelry" },
      { name: "Women's Jewelry" },
      { name: 'Watches' },
      { name: 'Rings' },
      { name: 'Necklaces' },
    ],
  },
];
export const attributeCategoryArr = [
  'color',
  'size',
  'material',
  'brand',
  'weight',
  'dimensions',
  'warranty',
  'gender',
  'ageGroup',
  'style',
  'batteryLife',
  'resolution',
  'capacity',
  'speed',
  'connectivity',
];

export const productAttributesArr = {
  color: [
    'red',
    'blue',
    'green',
    'yellow',
    'black',
    'white',
    'purple',
    'orange',
  ],
  size: ['small', 'medium', 'large', 'x-large', 'xx-large', 'xxx-large'],
  material: [
    'cotton',
    'polyester',
    'leather',
    'metal',
    'plastic',
    'wood',
    'glass',
  ],
  brand: ['nike', 'adidas', 'sony', 'samsung', 'apple', 'lg', 'dell', 'hp'],
  weight: ['500g', '1kg', '1.5kg', '2kg', '2.5kg', '3kg', '3.5kg'],
  dimensions: [
    '10x10x10cm',
    '20x20x20cm',
    '30x30x30cm',
    '40x40x40cm',
    '50x50x50cm',
  ],
  warranty: ['1 year', '2 years', '3 years', '5 years', 'lifetime'],
  gender: ['male', 'female', 'unisex'],
  ageGroup: ['kids', 'teens', 'adults', 'seniors', 'all ages'],
  style: ['casual', 'formal', 'sporty', 'elegant', 'modern', 'vintage'],
  batteryLife: ['1 hour', '2 hours', '5 hours', '10 hours', '24 hours'],
  resolution: ['720p', '1080p', '1440p', '4K', '8K'],
  capacity: ['16GB', '32GB', '64GB', '128GB', '256GB'],
  speed: ['1GHz', '2GHz', '3GHz', '4GHz', '5GHz'],
  connectivity: ['WiFi', 'Bluetooth', 'NFC', '4G', '5G'],
};
