export const homePath = '/';
export const productShowPath = (slug: string) => `/product/${slug}`;
export const productsTablePath = '/store/products';
export const discountsShowPath = '/store/discounts';
export const productsListPath = '/products';
export const productsListByCategoryPath = (slug: string) => `/c/${slug}`;
export const categoriesListPath = '/dashboard/categories';
export const myAddressesPath = '/account/addresses';
export const myReviewsPath = '/account/reviews';
export const myAccountSettingsPath = '/account/accountsettings';
export const cartPath = '/cart';
